# Generated by Django 3.0.4 on 2020-04-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20200412_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
