# Generated by Django 3.0.4 on 2020-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_remove_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=84957777777, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
