# Generated by Django 3.0.4 on 2020-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_auto_20200412_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=84957777777, max_digits=12, verbose_name='Номер телефона'),
        ),
    ]
