# Generated by Django 3.0.4 on 2020-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_auto_20200412_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация', null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
