# Generated by Django 3.0.4 on 2020-04-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='gift_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Имя получателя подарка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='gift_phone_number',
            field=models.DecimalField(decimal_places=0, default=84957777777, max_digits=12, verbose_name='Номер телефона'),
        ),
    ]
