# Generated by Django 3.0.4 on 2020-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_auto_20200418_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Номер телефона получателя подарка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Номер телефона'),
        ),
    ]
