# Generated by Django 3.0.4 on 2020-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_auto_20200418_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gift_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя получателя подарка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='Номер телефона получателя подарка'),
        ),
    ]
