# Generated by Django 3.0.4 on 2020-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_connectus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_page',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='connectus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='connectus',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
    ]
