# Generated by Django 3.0.4 on 2020-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200420_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Скидка указывается  в диапозоне от 0 до 100', null=True, verbose_name='Размер скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Акция'),
        ),
    ]
